### ISSUE TITLE
Show routes/dungeons differently if they have not been completed yet.

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker-dev#109]
Show the routes differently if they have yet to be completed.

Possible options:
An outline:
![image](https://user-images.githubusercontent.com/7288322/66263482-b5b35500-e84f-11e9-8427-815d1d087bf3.png)

Orange colour:
![image](https://user-images.githubusercontent.com/7288322/66263426-18582100-e84f-11e9-943b-9dc7e9469ee1.png)

Flashing effect:
![flash](https://user-images.githubusercontent.com/7288322/66263472-90264b80-e84f-11e9-9b31-d34cb2ceddc1.gif)

**Comment by Aegyo** [comment]
I like the orange best.

**Comment by Claygame** [comment]
orange color one is best as it is easy to detect

**Comment by RedSparr0w** [comment]
Orange color it is, now to figure out how to add it 😅

**Comment by aure2006** [comment]
@RedSparr0w 
https://files.catbox.moe/vv8jwj.txt
Edit: Forgot to add dungeons.

Screenshot: https://files.catbox.moe/8nnnak.png

**Comment by RedSparr0w** [comment]
Thanks @aure2006 
Did you want to join the discord where we are developing the project?
https://discord.gg/8y4hwFC

**Comment by aure2006** [comment]
Unfortunately I can't join discord because they don't allow my email address.

**Comment by RedSparr0w** [comment]
You don't need a verified email to join
