### ISSUE TITLE
Elite four name showing with numbers beside

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker-dev#116]
what hapen with his name? 
![Annotation 2019-10-13 171301](https://user-images.githubusercontent.com/56189709/66717814-91222480-eddd-11e9-9d46-d9582f2aed06.png)

**Comment by Popoteguitou** [comment]
and it's the same with bruno

**Comment by aure2006** [comment]
Duplicate of #86

**Comment by Popoteguitou** [comment]
nah
my issue say bruno's and lance's name are bugged, and #86 say about the image for all the elite 4

**Comment by RedSparr0w** [comment]
Note: Only happens when defeating for the first time, in the popup Modal.
