### ISSUE TITLE
Check for evolutions when traveling to next region

### ISSUE THREAD

**Issue by aure2006** [pokeclicker/pokeclicker-dev#125]
Since the level evolution check only runs when you level up, you need to breed pokemon like golbat and then train them again once you unlock the region for its evolution.
When I say "traveling to next region", I'm referring to the travelToNextRegion() function (which only runs when you unlock the next region) and not using the dock.

**Comment by RedSparr0w** [comment]
I think it's better to have to re-breed them.
Otherwise you would just all of a sudden gain a ton of extra Pokemon
