### ISSUE TITLE
Starter Choosing screen and Lost in Achievement Progress  [BUG] 

### ISSUE THREAD

**Issue by elitepokefans** [pokeclicker/pokeclicker-dev#139]
To make the picture more clearer I decided to merge both issues #133 and #138 as I think both are related.

I opened the test version game through the link
![image](https://user-images.githubusercontent.com/58838077/70855711-39ff1400-1f34-11ea-9910-ed17f023edeb.png)

Then a new window pops out the starter choosing screen appears and I click Next button
![image](https://user-images.githubusercontent.com/58838077/70855736-a37f2280-1f34-11ea-879b-3aa903788e41.png)

![image](https://user-images.githubusercontent.com/58838077/70855749-d88b7500-1f34-11ea-9946-bd7d8d37955e.png)

Choose my starter the same as first started then the screen straight away moves to defeat the chosen starter.  This screen then comes up and I click the Next button once more.

![image](https://user-images.githubusercontent.com/58838077/70855771-3750ee80-1f35-11ea-805e-66466d25e07a.png)

Begins to defeat pokemon on Route 1 and the town map is display.

![image](https://user-images.githubusercontent.com/58838077/70855789-8b5bd300-1f35-11ea-8198-d25f9334cab2.png)

Take a look on Routes 1 (dark orange colour being currently available route), 2 (red colour being unavailable route) and 22 (red colour being unavailable route). And all other Routes (yellow colour being already clear-off route).

And the achievements also looks like this for Route 1.

![image](https://user-images.githubusercontent.com/58838077/70855843-6c117580-1f36-11ea-8c38-fd76b3244060.png)

I have completed the 1st achievement on Route 1 of defeating 100 pokemon.
Take note of the 2nd and 3rd achievements in red colour.  
The counting of the 2nd achievement is 2/1000 and the 3rd achievement is 2/10000 meaning I have only defeated 2 pokemon in total.

**Comment by RedSparr0w** [comment]
Could you please update the title to better reflect the actual issue

**Comment by RedSparr0w** [comment]
If you could also upload your save file here too would be great 😄

**Comment by elitepokefans** [comment]
Upload my save file?  I am not sure how to attach a file into this.  I only learn to make and upload screen shots last night.

![image](https://user-images.githubusercontent.com/58838077/70856002-f22ebb80-1f38-11ea-941b-37e6fef69d83.png)

**Comment by RedSparr0w** [comment]
You can just drag and drop the file into the comment box here.

**Comment by elitepokefans** [comment]
Guess I did not do it right?
OK will try again.

[PokeClickerSave_2019-12-14 23_41_43.txt](https://github.com/pokeclicker-dev/pokeclicker/files/3964489/PokeClickerSave_2019-12-14.23_41_43.txt)
