### ISSUE TITLE
visual organisation

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker-dev#152]
battle item are in the right side, who is already full with oak items, quest and hatchery... but they are still some place on left side, where battle item (or quest) may fit nicely!

**Comment by RedSparr0w** [comment]
Sorry, i'm not 100% sure what you mean?

**Comment by Popoteguitou** [comment]
![Annotation 2019-12-16 205701](https://user-images.githubusercontent.com/56189709/70938542-a9652880-2046-11ea-9ae5-ce888e7dab6a.png)
clearer?

**Comment by RedSparr0w** [comment]
Ah, Yeah that shouldn't be a problem.
Just thinking about where the shortcuts menu should go too?
Will be a similar size to the Battle Items container.
But slightly larger.

**Comment by Popoteguitou** [comment]
🤔 may be some place here...
![Annotation 2019-12-16 210157](https://user-images.githubusercontent.com/56189709/70938953-8c7d2500-2047-11ea-9277-8b7fab9c8142.png)

**Comment by Popoteguitou** [comment]
it's were it was in old version, but you can also put it in start menu
