### ISSUE TITLE
Pokemons with big pic goes out of bounds

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#16]
Pic of big pokemons go out of line in list of pokemons

![image](https://user-images.githubusercontent.com/10423902/63355120-435fe180-c383-11e9-995e-5b4241ceaf48.png)

**Comment by RedSparr0w** [comment]
I've updated it to be slightly smaller (-10px on each side),
But otherwise the list becomes too large and doesn't look very nice.
