### ISSUE TITLE
Add Clefable in Mt Moon Dungeon

### ISSUE THREAD

**Issue by elitepokefans** [pokeclicker/pokeclicker-dev#175]
Currently Clefable is only obtainable through Moon Stone evolution.
Since both Clefairy and Clefable are supposed to be Mt Moon exclusive pokemon, it may make more sense to include Clefable as one of the final boss in that dungeon.

**Comment by Aegyo** [comment]
Clefable only appears in Mt. Moon in the Lets Go versions of Pokemon. I'm not sure which version we copied, but it definitely wasn't Lets Go.

https://bulbapedia.bulbagarden.net/wiki/Mt._Moon

**Comment by elitepokefans** [comment]
They (Clefairy and Clefable) are exclusive to Mt Moon since the very beginning, like when the game first came out in around 1999.  The official games are called Pokemon Red, Pokemon Blue and a little bit later Pokemon Yellow.  Let's Go versions of Pokemon are just the first Pokemon games introduced in their latest console Nintendo Switch.

**Comment by RedSparr0w** [comment]
Clafable doesn’t spawn there in the main series games.
https://m.bulbapedia.bulbagarden.net/wiki/Mt._Moon

**Comment by Popoteguitou** [comment]
damn, i'm sure i caugh one in fire red... and i never played let's go...
