### ISSUE TITLE
make all achievement counters accumulate over time

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#44]
idk how to word it right in the title so here i what i really mean.

right now many achievements such as number of diamonds, number of balls etc, require you to have the number required for the achievement to be present on you for them to count it as achievement.
there is achievement to collect 10000 diamonds, it will only make sense to have such achievement if all my past acquired diamonds are counted and not just my unspent diamonds in-hand right now.

**Comment by RedSparr0w** [comment]
Yup, This sounds fair enough to me.
