### ISSUE TITLE
double quest point bonus bug

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#56]
if you have a completed quest waiting for claim while your daily reset of quest happens, you get double the quest points of the unlcaimed finished quest.

it happens with lvl up of quest list too except that this time you get the double bonus if you lvl up from that finished quest claim

**Comment by RedSparr0w** [comment]
![image](https://user-images.githubusercontent.com/7288322/63979037-ff4fa800-cb0b-11e9-85c9-30958cf049fe.png)

**Comment by aure2006** [comment]
Daily refresh when you don't level up:
quitAllQuests
endQuest
clearQuests

Daily refresh when you do level up:
quitAllQuests
endQuest
refreshQuests
quitAllQuests
endQuest
clearQuests
clearQuests

You can fix it by moving this line to the top of the endQuest function:
player.currentQuests(player.currentQuests().filter(x => x.index != this.index));
