### ISSUE TITLE
a little edit on hatching message

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#78]
remove the "a" in this sentence since then you get the incorrect sentence when you hatch a pokemon such as Onix since it should be saying"an" in that sentence for onix

![image](https://user-images.githubusercontent.com/10423902/64796544-7c176300-d59d-11e9-92f4-ff79c4f33ce0.png)

**Comment by Aegyo** [comment]
Similar issue when capturing a pokemon I assume
