### ISSUE TITLE
gyarados and magikarp exp gain

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#79]
currently magikarp and gyarados require same amount of exp to reach lvl 100 which is not right as per pokemon data. Gyarados require almost a lot more exp than magikarp to get lvl 100.

i might be case for other pokemons too but i only just noticed these as i knew their exp required numbers.

**Comment by Aegyo** [comment]
Where are you getting that information from? Magikarp and Gyarados require the same amount of experience according to both serebii and bulbapedia.

**Comment by Claygame** [comment]
i said this so because of 2 reasons:
1. The general rule of pokemon that an evolved version of a pokemon always require more exp to lvl up than its previous evolution.

2. You can see the difference of required exp in these links:
Gyarados: https://pwo-wiki.info/index.php/Gyarados  (need 26438886 exp to hit lvl 100)
Magikarp: https://pwo-wiki.info/index.php/Magikarp (need 2470924 exp to hit lvl 100)

**Comment by Aegyo** [comment]
These links appear to be for "Pokemon World Online", not the official games.
These serebii links show that Magikarp and Gyarados are on the "slow" experience curve, which requires 1.25 million to reach lvl 100
https://www.serebii.net/pokedex-sm/129.shtml
https://www.serebii.net/pokedex-sm/130.shtml

**Comment by Claygame** [comment]
i dont see required exp on these page anywhere.. can we discuss more on discord?

Edit: NVM.. looks like my whole life was a lie and it is actually same for the pokemon throughtout its evolution.. i was told and believed they would require more to lvl if they are evolved..
