### ISSUE TITLE
quest list didnt got auto updated

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#87]
i completed all the quests in the list and the list didn't auto update to give me new list of quests.

![image](https://user-images.githubusercontent.com/10423902/65436619-0c786200-de40-11e9-94d8-3bfcc019e056.png)

**Comment by aure2006** [comment]
Is it supposed to?

**Comment by aure2006** [comment]
The quest list only refreshes if your quest level increases.

if (oldLevel < player.questLevel) {
	Notifier.notify("Your quest level has increased!", GameConstants.NotificationOption.success);
	QuestHelper.refreshQuests(true);
}
