### ISSUE TITLE
Very first time doing Brock gym fight does not end automatically

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker-dev#9]
When you fight the first gym while having the tutorial quest to defeat the first gym, the battle does no end on its own even if you defeat the leader. It ends after time runs out and it says you are not strong enough for the gym. After that it ends properly if you fight again and win.

![image](https://user-images.githubusercontent.com/10423902/63256551-6ad88080-c295-11e9-8a8a-a8d7d52f0645.png)

**Comment by RedSparr0w** [comment]
Are you able to reproduce this?

Couldn't get it to happen myself.

**Comment by Claygame** [comment]
i also tried a couple of times but seems like this is not happening anymore

**Comment by RedSparr0w** [comment]
Awesome!

I'll close this for now, we can always re-open if this is reproducable.
