### ISSUE TITLE
add why we can't access a location

### ISSUE THREAD

**Issue by Popoteguitou** [pokeclicker/pokeclicker-dev#97]
there are already message when we try to access a locked location, why not make it say why it's locked?

**Comment by aure2006** [comment]
@RedSparr0w 
https://files.catbox.moe/illiaj.txt

Screenshot: https://files.catbox.moe/8nnnak.png
You'll notice that it says Celadon City requires Ice Path dungeon, but I just temporarily added it as a requirement to test that the notification displayed the right text for towns.

**Comment by RedSparr0w** [comment]
Thanks @aure2006 👍 
Have made the change here: 66f2907e38cac468ac2ccf60ef3f64fa10293f15
